### ISSUE TITLE
Music Randomizer not working.

### ISSUE THREAD

**Issue by TheDarknives** [DefKorns/om_theme-selector#2]
Hey DefKorns, great job with the theme selector. I think I found an issue with music randomizer and not sure if it's just me but let me try to explain it.

After selecting Music Randomizer in the options, it simply does not recognize my music selection in my media/hakchi/menu_music folder. It worked pretty well with the Advanced Music Hack mod but, as in the description, that mod gets unistalled automatically after installig this mod, right?

I still see the Advanced Music Hack installed in my Extra Modules tho. So I tried manually uninstalling it and then reinstalling OM_Theme-Selector with no luck. My music doesn't play on the Home Screen or other places where it should be playing them.

Another thing. If I don't select Theme Randomizer in the settings to assign and play a theme to my named folders like super_nintendo, sega_genesis, arcade, etc. Each theme plays their respective background music, until the system switches to a theme without sound (that doesn't have Audio files on it, like the SnesCE ones or Zelda's ). It then picks the last theme's music.

For Example:

If I navigate to a folder with the 80's theme like my arcade's folder, all good with the theme and it's BG's music, but then If I select another folder with a Zelda theme or the SnesCE themes like my default home folder it plays it with that 80's theme. I guess it happens with the themes that doesn't have audio files like those. It always plays the last theme background music on those other soundless themes.

And last thing. I know Chrono Trigger's theme doesn't work with the Theme Randomizer setting. So if I set it to any of my game's folder, like super_nintendo for example, it gets me a C8 console error. The error persists on boot so I had to install "Boot to home" mod to pass from that error and tried another theme with super_nintendo. Is it because of CT's theme not working with Theme Randomizer or you think it should be working if assigned to a folder?

Thinks I've tried:
Following the written guide and Patton's steps. I Don't think this is an issue with the installation.
Uninstalling/reinstalling: options deluxe, om_theme selector and Advanced Music Hack mods.
Changing the theme settings.
Deleting the themes and reinstalling them on my USB, and reactivating them following the guides.
Assigning different themes to my game folders and Home default folder. 

Other than that, the mod works as intended. 

Here's my Modules Report.

[hmod_audit.txt](https://github.com/DefKorns/om_theme-selector/files/2835672/hmod_audit.txt)

**Comment by DefKorns** [comment]
Hi t@TheDarknives ,

audio randomizer only works on **home menu** and if the selected theme don't include any audio. 

Regarding the uninstallation of Advanced Music Hack, what version do you have installed? The one taht is already included on hakchice or the one downloaded from the mod store?

the uninstall feature for Advanced Music Hack, was developed assuming the version on hakchice. i can check for differences.

i'll look into the CT problem, i dont see why the c8, but i will recheck the code for issues.

Thank you

**Comment by TheDarknives** [comment]
> audio randomizer only works on **home menu** and if the selected theme don't include any audio.

Yeah, That's why I only used the Zelda themes or the SnesCE themes as default ones.

My folder structure looks like this [https://i.imgur.com/qI9UrH9.png](url)

And my themes folder on my USB like this: [https://i.imgur.com/FAuotIz.png](url)

Tried renaming snesce-jap to default.

> Regarding the uninstallation of Advanced Music Hack, what version do you have installed? The one taht is already included on hakchice or the one downloaded from the mod store?
 the uninstall feature for Advanced Music Hack, was developed assuming the version on hakchice. i can check for differences.

I tried with both actually. 
When I first tried the om_theme_selector I had Ver. 2.0.0. Uninstalled it, Tried the theme selector again with no go, and finally got 2.0.1 from the mod store. That's the one currently installed.

> i'll look into the CT problem, i dont see why the c8, but i will recheck the code for issues.

Thanks, it still gets me c8 after setting it on my super_nintendo folder.

**Comment by DefKorns** [comment]
@TheDarknives  i think i figured your audio issue
> Music files should be in PCM format, the naming of the music can be whatever you want as long **it don't have spaces** and the extension is .wav.

Your files names have spaces.

**Comment by TheDarknives** [comment]
Thanks, will try renaming the songs. They were working fine with the Advance Music Hack, but yes, I didn't follow that instruction with this mod.

**Comment by DefKorns** [comment]
i use a different way to select the files and it doesn't detect files with spaces on the name. . I'll try and update it to allow spaces (although this isn't a good practice ;))

**Comment by TheDarknives** [comment]
Yours is fine but yeah, that'd great, it can be troublesome for other users.

**Comment by TheDarknives** [comment]
Ok, I renamed the songs. https://i.imgur.com/zWc6ULw.png
Sadly didn't help. It's still not recognizing them in Home.

**Comment by DefKorns** [comment]
do you still have Hakchi Advanced Music Hack Installed?
 
1. Unisntall Hakchi Advanced Music Hack
2. Reinstall Theme Selector

**Comment by TheDarknives** [comment]
Yeah I still had it. the 2.0.1 ver. Uninstalled along with the deluxe options and theme selector mods. 
and reinstalled those 2, 1 by 1. First the Options menu, then the Theme selector.
What I also did is clear the snes theme folder on the usb to reinstall them.
Copied the SNES.all.tar.gz to snes folder.
Connected the usb with the adapter and turned on the snes.
Pressed L+R>Themes>Refresh. And selected snes loz gold theme.
Pressed L+R>Themes>Settings>Audio Randomizer> Close.
Didn't help so I turned off the console and turned it back on with the same result. Still not getting the audio files from the menu_music.

**Comment by DefKorns** [comment]
https://youtu.be/ByrsmdIR8_Q

**Comment by TheDarknives** [comment]
Thanks DefKorns, the video was pretty explanatory I see that it works for you and maybe will for other people as well.. This problem am having, just must be a particular issue for me. Don't know what's really happening because those are the steps I've been doing this whole time. Other than the music file name spaces issue I was having, not sure what else to try.
I think maybe try reinstalling Hakchi or keep trying with another USB or music files. The ones am using are PCM, 16 bit, and wav format files.  https://i.imgur.com/gytfZtX.png

The only differences I see is that you're using the EU snes while I have the US ver. but am sure that shouldn't be an issue and that your game folder structure is different than mine.

**Comment by DefKorns** [comment]
i'll send you a DM on reddit

**Comment by DefKorns** [comment]
@TheDarknives 
https://youtu.be/nX8Vc81n2uQ

i've been telling you the wrong folder name.  the folder must be ` music_menu`.  I was checking the code and noticed that.

**Comment by TheDarknives** [comment]
Ah that must be it then, nice catch. 
I'll rename the folder.

**Comment by DefKorns** [comment]
Thank you
