### ISSUE TITLE
Themes per folder 

### ISSUE THREAD

**Issue by Eskimoshowdown** [DefKorns/om_theme-selector#4]
hey defkorn! love love love the mod but i'm having some issues getting everything to work properly after hitting uninstall / clear list via the theme selector options menu. now i'm unable to set themes per folder by renaming them; i can only use one theme at a time by choosing it from the theme selector menu. also, im connected to wifi but am no longer able to populate themes to download - i have to manually create a themes folder and place them in there even after starting with a fresh install of everything. any help would be greatly appreciated and thanks for all your hard work! :)

running hakchi2-ce-3.5.2-debug
[hmod_audit.txt](https://github.com/DefKorns/om_theme-selector/files/2872191/hmod_audit.txt)

**Comment by DefKorns** [comment]
Hi @Eskimoshowdown, sorry for the delay but if been full of work.
Apparently, ModMyClassic had a issue with their servers and whent hey restored the backup it was very old.

This part is solved, i've checked myself on both NESCE and SNESCE.

now the other part,  i'm not sure i understood your issue but heres a a brief explanaintion how thing work:

- `Uninstall: this option removes the script that loads themes. useful when you want to start fresh`
- `Clear List: this option remes all the scripts from the themes. To repopulate the list with the themes on your system just use **Refresh**`
- To use theme per folder follow this [guide](https://github.com/DefKorns/om_theme-selector/wiki/Theme-per-folder)

Please keep me updated

**Comment by cgarst** [comment]
Having a similar issue, I think the Theme per folder guide is currently a little unclear. It seems like themes have to be FTP'ed to `/var/lib/hakchi/rootfs/usr/share/themes/snes` correct? The screenshots only show them in a `haxchi/themes/snes/` folder on PC.

Even still, after placing a couple themes there named the same as my folders I don't see the custom themes render on those folders. I'm not installing one through options menu because I want stock theme outside of the folders. Is another step is missing?

**Comment by cgarst** [comment]
^ On that note, my issue was not installing a base theme, in my case pulling in SNES.snesce-usa from ModMyClassic and installing that through the options menu. Then theme per folder worked.

**Comment by Eskimoshowdown** [comment]
Both issues resolved, thanks! Keep up the good work! :D

**Comment by DefKorns** [comment]
> Having a similar issue, I think the Theme per folder guide is currently a little unclear. It seems like themes have to be FTP'ed to `/var/lib/hakchi/rootfs/usr/share/themes/snes` correct? The screenshots only show them in a `haxchi/themes/snes/` folder on PC.

`/var/lib/hakchi/rootfs/usr/share/themes/snes` is only if you want themes on NAND.

The README file on the [How do i use it](https://github.com/DefKorns/om_theme-selector/blob/master/README.md#how-do-i-use-it)  section is very clear about this ;)
