### ISSUE TITLE
Options Menu (screen freezes when use L&R)

### ISSUE THREAD

**Issue by Ziggy6654** [DefKorns/om_theme-selector#5]
I have the latest hakchi CE , I followed Patton’s video on how to change the theme on my NES and SNES Classic but after installing the option theme selector menu 1.3 or 1.2 pressing L&R only make the screen freeze. I don’t know if I am doing something wrong.

**Comment by DefKorns** [comment]
For latest hakchi you need to use options menu 1.3.4+.
https://github.com/CompCom/OptionsMenu/releases/tag/1.3.4

**Comment by Ziggy6654** [comment]
Thank you!

Sent from my iPhone 8

On Aug 1, 2020, at 6:34 AM, defkorns <notifications@github.com> wrote:

﻿
Closed #5.
