### ISSUE TITLE
Options menu wont open.

### ISSUE THREAD

**Issue by RetroWave1736** [DefKorns/om_theme-selector#6]
So I was trying to get the custom themes but when i add the Options Deluxe .homd file to hakchi, the file doesnt appear. So i activate all the system stuff but it still wont open. How do i fix it?

**Comment by DefKorns** [comment]
This issue is not related with theme selector. But on our FAQ there is a fix to it.

https://github.com/DefKorns/om_theme-selector/wiki/FAQ#i-press-and-hold-lr-down--b-on-nesce-and-nothing-happens
